config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # defaults to dashboard
  # root :to => redirect('/dashboard')

  get 'welcome/index'
 
  root 'welcome#index'
  
  # view routes
  resources :sensors
  resources :makers
  resources :map
  resources :charts
  resources :triggers
  resources :cubes

  
  get '/dashboard' => 'dashboard#index'
  get '/triggers' => 'triggers#index'
  get '/billing' => 'billing#index' 
  get '/checkout'   => 'billing#checkout'
  get '/success'   => 'billing#success'
  get '/payment' => 'payment#index'
  post '/addcreditcard' => 'payment#addcreditcard'
  get '/deletecreditcard' => 'payment#deletecreditcard'
  get '/registercube' => 'cubes#register'

  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"

  get '/register', to: 'makers#new'
  get '/sensors/:id/destroy', to: 'sensors#destroy'
  get '/triggers/:id/destroy', to: 'triggers#destroy'
  get '/cubes/:id/destroy', to: 'cubes#destroy'

  get '/makers/:id/destroy', to: 'makers#destroy'

  
  # api routes
  get '/api/i18n/:locale' => 'api#i18n'
  get '/api/setsensorpropertyvalue' => "apis#setsensorpropertyvalue"
  get '/api/setsigfoxsensorvalue' => "apis#setsigfoxsensorvalue"
  get '/api/createtimeseries' => "apis#createtimeseries"
  get '/api/testhttprequest' => "apis#testhttprequest"

  post '/api/set_ttn_sensor_value' => "apis#setttnsensorvalue"
  post '/api/set_ttn_node' => "apis#setttnnode"

end

app/models/sensor.rb
class Sensor < ActiveRecord::Base
  belongs_to :maker

  validates :maker_id, presence: true
  validates :cube_id, presence: true
  validates :name, presence: true, length: {minimum: 5, maximum: 100 }

end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
before_action :set_sensor, only: [ :update, :show, :like, :destroy]
before_action :require_same_user, only: [ :update]
before_action :set_maker, only: [:show, :destroy]
before_action :build_sensor_image_map
before_action :build_sensor_naming_map
before_action :build_sensor_measure_map
before_action :require_user
before_action :list_available_cubes

    
    def index
        
        @sensors = Sensor.all
    
    end
    
    def show
        @sensor = Sensor.find(params[:id])
        @triggers = @sensor.triggers
        
        @shiftrsrc = "https://shiftr.io/" + @sensor.namespace + "/embed?zoom=1"
    end
    
    def temp
        @sensor = Sensor.find(params[:id])
        render :text => @sensor.property.value
    end
    
    def new
        @sensor = Sensor.new   
    end

    def edit
      @sensor = Sensor.find(params[:id])
      puts "At least it's calling edit"
    end
    
    def create
        @sensor = Sensor.new(sensor_params)
        @sensor.maker = current_user

        cube = Cube.find(sensor_params[:cube_id])
        @sensor.arduino_id = cube.board_id.to_s + '-' + @sensor_naming[sensor_params[:sensor_type]].to_s
        puts cube.board_id.to_s + '-' + @sensor_naming[sensor_params[:sensor_type]].to_s
  
        if @sensor.save
          flash[:success] = "Your sensor was created: " 
          redirect_to dashboard_path
          
        else
          render :new
        end
    end
    

    
    def update

        cube = Cube.find(sensor_params[:cube_id])
        @sensor.arduino_id = cube.board_id.to_s + '-' + @sensor_naming[sensor_params[:sensor_type]].to_s
        puts cube.board_id.to_s + '-' + @sensor_naming[sensor_params[:sensor_type]].to_s
        @sensor.save

        if @sensor.update(sensor_params)   

          flash[:success] = "Your sensor was updated successfully!"
          redirect_to dashboard_path
        else
          render :edit
        end
    
    end

    
    def destroy
        sensor_id = params[:id]
        TimeSeries.where(sensor_id: sensor_id).delete_all
        Sensor.find(sensor_id).destroy
        flash[:success] = "Sensor deleted"
        redirect_to dashboard_path
    end
    
    
  
    def sensor_params
      params.require(:sensor).permit(:name, :sensor_type, :altitude, :latitude, :longitude, :cube_id)
    end
    
    def set_sensor
      @sensor = Sensor.find(params[:id])
    end
    
    
    def set_maker
      @maker = @sensor.maker
    end

    def list_available_cubes
      @cubes = Cube.where(maker_id: current_user.id)
    end
    
    
    def require_same_user
      if current_user != @sensor.maker
        flash[:danger] = "You can only edit your own sensors"
        redirect_to dashboard_path
      end
    end

    def build_sensor_image_map
      @sensor_image = Hash.new
      @sensor_image["Temperature"] = "icons8-thermometer-automation-96.png"
      @sensor_image["Pressure"] = "icons8-pressure-96.png"
      @sensor_image["Humidity"] = "icons8-rain-96.png" 
      @sensor_image["WaterproofTemperature"] = "icons8-thermometer-automation-96.png"
      @sensor_image["SoilMoisture"] = "icons8-water-96.png"
      @sensor_image["LightIntensity"] = "icons8-light-on-96.png"
      @sensor_image["AirQuality"] = "icons8-air-quality-96.png"
      @sensor_image["Power"] = "icons8-electrical-96.png"
      @sensor_image["Battery"] = "icons8-charging-battery-96.png"
      

    end


    def build_sensor_naming_map
      @sensor_naming = Hash.new
      @sensor_naming["Temperature"] = "01"
      @sensor_naming["Pressure"] = "02"
      @sensor_naming["Humidity"] = "03"
      @sensor_naming["WaterproofTemperature"] = "04"
      @sensor_naming["SoilMoisture"] = "05"
      @sensor_naming["LightIntensity"] = "06"
      @sensor_naming["AirQuality"] = "07"
      @sensor_naming["Power"] = "08"
      @sensor_naming["Battery"] = "09"

    end

    def build_sensor_measure_map
      @sensor_measure = Hash.new
      @sensor_measure["Temperature"] = "&deg;C"
      @sensor_measure["Pressure"] = "hPa"
      @sensor_measure["Humidity"] = "%"
      @sensor_measure["WaterproofTemperature"] = "&deg;C"
      @sensor_measure["SoilMoisture"] = ""
      @sensor_measure["LightIntensity"] = ""
      @sensor_measure["Air Quality"] = ""
      @sensor_measure["Power-sensor"] = ""
      @sensor_measure["Battery"] = ""
    end

end

app/views/sensors/_form.html.erb
<div class="container">
<%= render 'shared/errors', obj: @sensor %>

<div class="row">
  
  
  <div class="well col-md-4 col-md-offset-4">
    <%= form_for(@sensor, html: { multipart: true }) do |s| %>

    <%= s.label :cube_id %>
    <%= s.select :cube_id, @cubes.all.collect { |c| [ c.name, c.id ] }, include_blank: true %>
    <br>



      <%= s.label :name %>
      <%= s.text_field :name %>

      <%= s.label :altitude %>
      <%= s.text_field :altitude %>



      <%= s.label :sensor_type %>
      <%= s.select :sensor_type,
          [ 'Temperature', 
            'Humidity', 
            'Pressure', 
            'WaterproofTemperature', 
            'SoilMoisture', 
            'LightIntensity', 
            'AirQuality',
            'Power',
            'Battery'] %>  


     
      <%= s.submit(@sensor.new_record? ? 'Create Sensor' : 'Edit Sensor', class: "btn btn-success") %>
      <div class="btn btn-success white"><%= link_to 'Delete', "/sensors/#{@sensor.id}/destroy" %></div>
    <% end %>
  </div>
</div>
</div>

  

app/views/sensors/edit.html.erb
<%= render 'shared/nav_top' %>
<%= render 'shared/nav_side' %>
<%= render 'shared/flash'%>

<%= render 'form' %>

<script>
       $(document).ready(function(){
    $('.sidenav').sidenav();
    $('select').formSelect();
  });
</script>

app/views/sensors/index.html.erb
<h1>All Sensors</h1>
<hr/>

<div class="container white_pane">
 

      
    


    <% @sensors.each do |sensor| %>
        

          <div class="col-md-3">
              
              <div class="thermostat_gallery"><%= sensor.max_temperature  %></div>
              <div class="thermostat_gallery_name",margin-left=30px><%= link_to sensor.name, sensor_path(sensor) %></div>
          </div> 
    
    <% end %>
</div>

app/views/sensors/new.html.erb
<%= render 'shared/nav_top' %>
<%= render 'shared/nav_side' %>
<%= render 'shared/flash'%>

<%= render 'form' %>

<script>
       $(document).ready(function(){
    $('.sidenav').sidenav();
    $('select').formSelect();
  });
</script>

app/views/sensors/show.html.erb
    

<p>
    <h2><%= @sensor.name %></h2>
</p>

<div class="row">
    <div class="col-md-2 pull-left center">
        <div class="thermostat_gallery">&nbsp<%= number_with_precision(@sensor.max_temperature,:precision => 1)  %>
        <br>
        <font size="2"><%= @sensor.property_value %></font>
        </div>
        
        
        
        
    </div>
    <div class="col-md-4">
        <h4>Sensor settings</h4>
        <div class="well">
            <p> Name: <%= @sensor.name %></p>
            <p> Temperature: <%= @sensor.property_value %></p>
            <p> Max Temperature: <%= number_with_precision(@sensor.max_temperature,:precision => 1) %></p>
            <p> Interval: <%= @sensor.interval %></p>
            <p> Namespace: <%= @sensor.namespace %></p>
            <p> MQTT username: <%= @sensor.mqtt_user %></p>
            <p> MQTT password: <%= @sensor.mqtt_password %></p>
            <p> IFTTT Trigger URL: <%= @sensor.ifttt %></p>
           
        </div>
    </div> 
    
    <div class="col-md-4">
        <h4>Sensor triggers</h4>
        <div class="well">
            <% @triggers.each do |trigger| %>
                <p> Name: <%= trigger.name %></p>
                <p> Value: <%= trigger.value %></p>
                <p> Webhook URL: <%= trigger.webhook_url %></p>
            <% end %>
        </div>
    </div>
    
    
    
    
    
</div>
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-sm-2 text-left pull-left">
                <%= link_to '', new_trigger_path(:sensor => @sensor), class: "glyphicon glyphicon-flash" %>
                &nbsp;&nbsp;
                <%= link_to '', edit_sensor_path(@sensor), class: "glyphicon glyphicon-wrench" %>
                &nbsp;&nbsp;
                <%= link_to "",  @sensor, class: "glyphicon glyphicon-trash", method: :delete,data: { confirm: "You sure?" } %>
    </div>
 </div> 
 
 <hr>
        
<div class="row">
     <div class="col-md-2 pull-left center">
       
    </div>
    <div class="col-md-8">
        <iframe src= <%= @shiftrsrc %>
            width="600" 
            height="400" 
            frameborder="0" 
            webkitallowfullscreen 
            mozallowfullscreen 
            allowfullscreen
        </iframe>
    </div>
</div>